# import libraries

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer

In [2]:
from datasets import load_dataset

dataset = load_dataset("tweet_eval", "emotion")

Found cached dataset tweet_eval (C:/Users/User/.cache/huggingface/datasets/tweet_eval/emotion/1.1.0/12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343)


  0%|          | 0/3 [00:00<?, ?it/s]

In [3]:
dataset["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 3257
})

In [4]:
dataset["test"]

Dataset({
    features: ['text', 'label'],
    num_rows: 1421
})

In [5]:
dataset["validation"]

Dataset({
    features: ['text', 'label'],
    num_rows: 374
})

In [6]:
from transformers import AutoTokenizer

# Load a pre-trained tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")


In [7]:
def tokenize_function(example):
    return tokenizer(example["text"], padding="max_length", truncation=True, max_length=128)


In [8]:
# Tokenize the dataset
tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Get the input_ids from the tokenized dataset for train, validation, and test sets
train_input_ids = [example['input_ids'] for example in tokenized_dataset['train']]
val_input_ids = [example['input_ids'] for example in tokenized_dataset['validation']]
test_input_ids = [example['input_ids'] for example in tokenized_dataset['test']]

# Convert input_ids to PyTorch tensors
train_input_ids = torch.tensor(train_input_ids, dtype=torch.long)
val_input_ids = torch.tensor(val_input_ids, dtype=torch.long)
test_input_ids = torch.tensor(test_input_ids, dtype=torch.long)

# Concatenate the input_ids tensors along the first dimension
input_ids = torch.cat((train_input_ids, val_input_ids, test_input_ids), dim=0)


Loading cached processed dataset at C:\Users\User\.cache\huggingface\datasets\tweet_eval\emotion\1.1.0\12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343\cache-9d05afcd1051738d.arrow
Loading cached processed dataset at C:\Users\User\.cache\huggingface\datasets\tweet_eval\emotion\1.1.0\12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343\cache-eea42245fea12e4d.arrow
Loading cached processed dataset at C:\Users\User\.cache\huggingface\datasets\tweet_eval\emotion\1.1.0\12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343\cache-a217fece7ee692df.arrow


In [9]:
# Tokenize the dataset
tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Get the attention_masks from the tokenized dataset for train, validation, and test sets
train_attention_mask = [example['attention_mask'] for example in tokenized_dataset['train']]
val_attention_mask = [example['attention_mask'] for example in tokenized_dataset['validation']]
test_attention_mask = [example['attention_mask'] for example in tokenized_dataset['test']]

# Convert attention_mask to PyTorch tensors
train_attention_mask = torch.tensor(train_attention_mask, dtype=torch.long)
val_attention_mask = torch.tensor(val_attention_mask, dtype=torch.long)
test_attention_mask = torch.tensor(test_attention_mask, dtype=torch.long)

# Concatenate the input_ids tensors along the first dimension
attention_masks = torch.cat((train_attention_mask, val_attention_mask, test_attention_mask), dim=0)


Loading cached processed dataset at C:\Users\User\.cache\huggingface\datasets\tweet_eval\emotion\1.1.0\12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343\cache-9d05afcd1051738d.arrow
Loading cached processed dataset at C:\Users\User\.cache\huggingface\datasets\tweet_eval\emotion\1.1.0\12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343\cache-eea42245fea12e4d.arrow
Loading cached processed dataset at C:\Users\User\.cache\huggingface\datasets\tweet_eval\emotion\1.1.0\12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343\cache-a217fece7ee692df.arrow


In [10]:
print(input_ids)

tensor([[  101,   789,   160,  ...,     0,     0,     0],
        [  101,  1422, 20116,  ...,     0,     0,     0],
        [  101,  1302,  1133,  ...,     0,     0,     0],
        ...,
        [  101,  9202,   170,  ...,     0,     0,     0],
        [  101,  1398,  1142,  ...,     0,     0,     0],
        [  101,  5718,  1129,  ...,     0,     0,     0]])


In [11]:
print(attention_masks)

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])


In [12]:
# Split the dataset into train, validation, and test sets
train_dataset = tokenized_dataset["train"]
val_dataset = tokenized_dataset["validation"]
test_dataset = tokenized_dataset["test"]

In [13]:
print(input_ids)

tensor([[  101,   789,   160,  ...,     0,     0,     0],
        [  101,  1422, 20116,  ...,     0,     0,     0],
        [  101,  1302,  1133,  ...,     0,     0,     0],
        ...,
        [  101,  9202,   170,  ...,     0,     0,     0],
        [  101,  1398,  1142,  ...,     0,     0,     0],
        [  101,  5718,  1129,  ...,     0,     0,     0]])


In [14]:
# Convert the datasets to PyTorch tensors
train_dataset = train_dataset.remove_columns(["text"])
val_dataset = val_dataset.remove_columns(["text"])
test_dataset = test_dataset.remove_columns(["text"])

In [15]:
train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

In [16]:
import torch.nn as nn
from transformers import BertModel

class EmotionDetectionModel(nn.Module):
    def __init__(self, num_classes=4):
        super(EmotionDetectionModel, self).__init__()
        self.bert = BertModel.from_pretrained('bert-base-uncased')
        self.dropout = nn.Dropout(0.1)
        self.fc = nn.Linear(self.bert.config.hidden_size, num_classes)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.pooler_output
        pooled_output = self.dropout(pooled_output)
        logits = self.fc(pooled_output)
        return logits


In [17]:
print(input_ids)

tensor([[  101,   789,   160,  ...,     0,     0,     0],
        [  101,  1422, 20116,  ...,     0,     0,     0],
        [  101,  1302,  1133,  ...,     0,     0,     0],
        ...,
        [  101,  9202,   170,  ...,     0,     0,     0],
        [  101,  1398,  1142,  ...,     0,     0,     0],
        [  101,  5718,  1129,  ...,     0,     0,     0]])


In [18]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


In [19]:
# instantiate your model
emotion_model = EmotionDetectionModel(num_classes=4).to(device)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [20]:
print(emotion_model)

EmotionDetectionModel(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

In [21]:
# define your loss function
criterion = nn.CrossEntropyLoss()

# define your optimizer
optimizer = torch.optim.Adam(emotion_model.parameters(), lr=0.001)

In [22]:
# set up your training, validation, and test dataloaders
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)
test_loader = DataLoader(test_dataset, batch_size=16)

In [23]:
print(input_ids)

tensor([[  101,   789,   160,  ...,     0,     0,     0],
        [  101,  1422, 20116,  ...,     0,     0,     0],
        [  101,  1302,  1133,  ...,     0,     0,     0],
        ...,
        [  101,  9202,   170,  ...,     0,     0,     0],
        [  101,  1398,  1142,  ...,     0,     0,     0],
        [  101,  5718,  1129,  ...,     0,     0,     0]])


In [24]:
print(attention_masks)

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])


In [25]:
for batch in train_loader:
    print(batch)


{'label': tensor([3, 1, 0, 0, 0, 0, 1, 0, 3, 1, 1, 0, 1, 0, 0, 3]), 'input_ids': tensor([[  101, 18896,  3690,  ...,     0,     0,     0],
        [  101, 10616,  1110,  ...,     0,     0,     0],
        [  101,  1220,  1328,  ...,     0,     0,     0],
        ...,
        [  101,   137,  4795,  ...,     0,     0,     0],
        [  101, 11907, 25685,  ...,     0,     0,     0],
        [  101, 20735,  3650,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}
{'label': tensor([0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 1, 3, 2, 0, 0, 0]), 'input_ids': tensor([[ 101, 2119,  137,  ...,    0,    0,    0],
        [ 101, 2814,  106,  ...,    0,    0,    0],
        [ 101,  137, 4795,  ...,    0,    0,    0],
        ...,
        [ 101,  180, 1424,  ...,    0,    0,    0],
        [ 101,  1

In [26]:
from tqdm import tqdm
num_epochs = 1
for epoch in range(num_epochs):
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0
    for batch in tqdm(train_loader, desc=f'Epoch {epoch+1}/{num_epochs}'):
        # get the inputs
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = emotion_model(input_ids=input_ids, attention_mask=attention_mask)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # calculate accuracy
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

        # print running loss for each batch
        running_loss += loss.item()
        avg_loss = running_loss / len(train_loader)
        avg_acc = correct_predictions / total_predictions
        tqdm.write(f'Train Loss: {avg_loss:.3f}, Train Acc: {avg_acc:.3f}', end='\r')
    tqdm.write(f'Epoch {epoch+1}, Train Loss: {avg_loss:.3f}, Train Acc: {avg_acc:.3f}')

    print(f"Epoch {epoch+1} finished")


Epoch 1/1:   0%|          | 1/204 [00:17<57:31, 17.00s/it]

Epoch 1/1:   1%|          | 2/204 [00:32<53:34, 15.91s/it]

Epoch 1/1:   1%|▏         | 3/204 [00:46<51:18, 15.32s/it]

Epoch 1/1:   2%|▏         | 4/204 [01:00<49:16, 14.78s/it]

Epoch 1/1:   2%|▏         | 5/204 [01:14<48:09, 14.52s/it]

Epoch 1/1:   3%|▎         | 6/204 [01:29<48:32, 14.71s/it]

Epoch 1/1:   3%|▎         | 7/204 [01:47<51:51, 15.79s/it]

Epoch 1/1:   4%|▍         | 8/204 [02:04<52:12, 15.98s/it]

Epoch 1/1:   4%|▍         | 9/204 [02:19<51:11, 15.75s/it]

Epoch 1/1:   5%|▍         | 10/204 [02:38<53:55, 16.68s/it]

Epoch 1/1:   5%|▌         | 11/204 [03:01<59:45, 18.58s/it]

Epoch 1/1:   6%|▌         | 12/204 [03:25<1:04:51, 20.27s/it]

Epoch 1/1:   6%|▋         | 13/204 [03:52<1:11:06, 22.34s/it]

Epoch 1/1:   7%|▋         | 14/204 [04:15<1:11:45, 22.66s/it]

Epoch 1/1:   7%|▋         | 15/204 [04:39<1:12:34, 23.04s/it]

Epoch 1/1:   8%|▊         | 16/204 [05:03<1:12:54, 23.27s/it]

Epoch 1/1:   8%|▊         | 17/204 [05:26<1:12:23, 23.23s/it]

Epoch 1/1:   9%|▉         | 18/204 [05:49<1:11:55, 23.20s/it]

Epoch 1/1:   9%|▉         | 19/204 [06:13<1:11:34, 23.21s/it]

Epoch 1/1:  10%|▉         | 20/204 [06:36<1:11:26, 23.30s/it]

Epoch 1/1:  10%|█         | 21/204 [07:04<1:14:58, 24.58s/it]

Epoch 1/1:  11%|█         | 22/204 [07:27<1:13:19, 24.18s/it]

Epoch 1/1:  11%|█▏        | 23/204 [07:50<1:12:12, 23.94s/it]

Epoch 1/1:  12%|█▏        | 24/204 [08:14<1:11:44, 23.91s/it]

Epoch 1/1:  12%|█▏        | 25/204 [08:37<1:10:46, 23.72s/it]

Epoch 1/1:  13%|█▎        | 26/204 [09:01<1:10:18, 23.70s/it]

Epoch 1/1:  13%|█▎        | 27/204 [09:24<1:09:36, 23.60s/it]

Epoch 1/1:  14%|█▎        | 28/204 [09:47<1:08:42, 23.42s/it]

Epoch 1/1:  14%|█▍        | 29/204 [10:11<1:08:08, 23.36s/it]

Epoch 1/1:  15%|█▍        | 30/204 [10:34<1:07:44, 23.36s/it]

Epoch 1/1:  15%|█▌        | 31/204 [10:57<1:07:20, 23.36s/it]

Epoch 1/1:  16%|█▌        | 32/204 [11:21<1:06:53, 23.34s/it]

Epoch 1/1:  16%|█▌        | 33/204 [11:44<1:06:39, 23.39s/it]

Epoch 1/1:  17%|█▋        | 34/204 [12:08<1:06:30, 23.47s/it]

Epoch 1/1:  17%|█▋        | 35/204 [12:31<1:06:01, 23.44s/it]

Epoch 1/1:  18%|█▊        | 36/204 [12:54<1:05:28, 23.38s/it]

Epoch 1/1:  18%|█▊        | 37/204 [13:18<1:04:53, 23.31s/it]

Epoch 1/1:  19%|█▊        | 38/204 [13:41<1:04:21, 23.26s/it]

Epoch 1/1:  19%|█▉        | 39/204 [14:04<1:03:53, 23.23s/it]

Epoch 1/1:  20%|█▉        | 40/204 [14:28<1:04:19, 23.53s/it]

Epoch 1/1:  20%|██        | 41/204 [14:51<1:03:34, 23.40s/it]

Epoch 1/1:  21%|██        | 42/204 [15:14<1:02:59, 23.33s/it]

Epoch 1/1:  21%|██        | 43/204 [15:38<1:02:32, 23.30s/it]

Epoch 1/1:  22%|██▏       | 44/204 [16:02<1:02:52, 23.58s/it]

Epoch 1/1:  22%|██▏       | 45/204 [16:25<1:02:07, 23.44s/it]

Epoch 1/1:  23%|██▎       | 46/204 [16:48<1:01:42, 23.43s/it]

Epoch 1/1:  23%|██▎       | 47/204 [17:12<1:01:15, 23.41s/it]

Epoch 1/1:  24%|██▎       | 48/204 [17:35<1:00:52, 23.41s/it]

Epoch 1/1:  24%|██▍       | 49/204 [17:58<1:00:25, 23.39s/it]

Epoch 1/1:  25%|██▍       | 50/204 [18:22<59:55, 23.35s/it]  

Epoch 1/1:  25%|██▌       | 51/204 [18:45<59:18, 23.26s/it]

Epoch 1/1:  25%|██▌       | 52/204 [19:08<58:58, 23.28s/it]

Epoch 1/1:  26%|██▌       | 53/204 [19:31<58:35, 23.28s/it]

Epoch 1/1:  26%|██▋       | 54/204 [19:54<58:03, 23.22s/it]

Epoch 1/1:  27%|██▋       | 55/204 [20:19<58:38, 23.62s/it]

Epoch 1/1:  27%|██▋       | 56/204 [20:44<59:21, 24.06s/it]

Epoch 1/1:  28%|██▊       | 57/204 [21:07<58:26, 23.85s/it]

Epoch 1/1:  28%|██▊       | 58/204 [21:31<57:29, 23.63s/it]

Epoch 1/1:  29%|██▉       | 59/204 [21:54<56:55, 23.56s/it]

Epoch 1/1:  29%|██▉       | 60/204 [22:17<56:26, 23.51s/it]

Epoch 1/1:  30%|██▉       | 61/204 [22:41<55:59, 23.50s/it]

Epoch 1/1:  30%|███       | 62/204 [23:04<55:37, 23.50s/it]

Epoch 1/1:  31%|███       | 63/204 [23:33<58:32, 24.91s/it]

Epoch 1/1:  31%|███▏      | 64/204 [23:56<57:13, 24.52s/it]

Epoch 1/1:  32%|███▏      | 65/204 [24:19<55:44, 24.06s/it]

Epoch 1/1:  32%|███▏      | 66/204 [24:43<55:01, 23.92s/it]

Epoch 1/1:  33%|███▎      | 67/204 [25:06<54:00, 23.65s/it]

Epoch 1/1:  33%|███▎      | 68/204 [25:29<53:11, 23.47s/it]

Epoch 1/1:  34%|███▍      | 69/204 [25:52<52:21, 23.27s/it]

Epoch 1/1:  34%|███▍      | 70/204 [26:15<52:17, 23.41s/it]

Epoch 1/1:  35%|███▍      | 71/204 [26:38<51:38, 23.29s/it]

Epoch 1/1:  35%|███▌      | 72/204 [27:01<51:08, 23.25s/it]

Epoch 1/1:  36%|███▌      | 73/204 [27:25<50:39, 23.20s/it]

Epoch 1/1:  36%|███▋      | 74/204 [27:48<50:21, 23.24s/it]

Epoch 1/1:  37%|███▋      | 75/204 [28:11<49:51, 23.19s/it]

Epoch 1/1:  37%|███▋      | 76/204 [28:34<49:24, 23.16s/it]

Epoch 1/1:  38%|███▊      | 77/204 [28:57<49:05, 23.19s/it]

Epoch 1/1:  38%|███▊      | 78/204 [29:20<48:40, 23.18s/it]

Epoch 1/1:  39%|███▊      | 79/204 [29:45<48:54, 23.48s/it]

Epoch 1/1:  39%|███▉      | 80/204 [30:08<48:22, 23.41s/it]

Epoch 1/1:  40%|███▉      | 81/204 [30:31<47:46, 23.31s/it]

Epoch 1/1:  40%|████      | 82/204 [30:54<47:20, 23.28s/it]

Epoch 1/1:  41%|████      | 83/204 [31:18<47:01, 23.32s/it]

Epoch 1/1:  41%|████      | 84/204 [31:41<46:34, 23.29s/it]

Epoch 1/1:  42%|████▏     | 85/204 [32:04<46:07, 23.26s/it]

Epoch 1/1:  42%|████▏     | 86/204 [32:27<45:45, 23.27s/it]

Epoch 1/1:  43%|████▎     | 87/204 [32:51<45:26, 23.30s/it]

Epoch 1/1:  43%|████▎     | 88/204 [33:14<44:58, 23.27s/it]

Epoch 1/1:  44%|████▎     | 89/204 [33:37<44:35, 23.27s/it]

Epoch 1/1:  44%|████▍     | 90/204 [34:00<44:13, 23.27s/it]

Epoch 1/1:  45%|████▍     | 91/204 [34:24<43:51, 23.28s/it]

Epoch 1/1:  45%|████▌     | 92/204 [34:47<43:26, 23.28s/it]

Epoch 1/1:  46%|████▌     | 93/204 [35:10<43:09, 23.33s/it]

Epoch 1/1:  46%|████▌     | 94/204 [35:34<42:42, 23.30s/it]

Epoch 1/1:  47%|████▋     | 95/204 [35:59<43:12, 23.78s/it]

Epoch 1/1:  47%|████▋     | 96/204 [36:22<42:51, 23.81s/it]

Epoch 1/1:  48%|████▊     | 97/204 [36:46<42:12, 23.67s/it]

Epoch 1/1:  48%|████▊     | 98/204 [37:09<41:43, 23.62s/it]

Epoch 1/1:  49%|████▊     | 99/204 [37:33<41:18, 23.60s/it]

Epoch 1/1:  49%|████▉     | 100/204 [37:56<40:55, 23.61s/it]

Epoch 1/1:  50%|████▉     | 101/204 [38:20<40:30, 23.59s/it]

Epoch 1/1:  50%|█████     | 102/204 [38:44<40:08, 23.62s/it]

Epoch 1/1:  50%|█████     | 103/204 [39:07<39:44, 23.61s/it]

Epoch 1/1:  51%|█████     | 104/204 [39:31<39:23, 23.63s/it]

Epoch 1/1:  51%|█████▏    | 105/204 [39:55<39:04, 23.68s/it]

Epoch 1/1:  52%|█████▏    | 106/204 [40:18<38:41, 23.69s/it]

Epoch 1/1:  52%|█████▏    | 107/204 [40:42<38:11, 23.62s/it]

Epoch 1/1:  53%|█████▎    | 108/204 [41:07<38:15, 23.92s/it]

Epoch 1/1:  53%|█████▎    | 109/204 [41:30<37:41, 23.80s/it]

Epoch 1/1:  54%|█████▍    | 110/204 [41:54<37:09, 23.72s/it]

Epoch 1/1:  54%|█████▍    | 111/204 [42:17<36:47, 23.74s/it]

Epoch 1/1:  55%|█████▍    | 112/204 [42:41<36:16, 23.66s/it]

Epoch 1/1:  55%|█████▌    | 113/204 [43:04<35:50, 23.63s/it]

Epoch 1/1:  56%|█████▌    | 114/204 [43:28<35:23, 23.60s/it]

Epoch 1/1:  56%|█████▋    | 115/204 [43:52<35:01, 23.61s/it]

Epoch 1/1:  57%|█████▋    | 116/204 [44:15<34:35, 23.58s/it]

Epoch 1/1:  57%|█████▋    | 117/204 [44:38<34:06, 23.52s/it]

Epoch 1/1:  58%|█████▊    | 118/204 [45:02<33:45, 23.55s/it]

Epoch 1/1:  58%|█████▊    | 119/204 [45:27<33:47, 23.86s/it]

Epoch 1/1:  59%|█████▉    | 120/204 [45:50<33:21, 23.83s/it]

Epoch 1/1:  59%|█████▉    | 121/204 [46:14<32:49, 23.73s/it]

Epoch 1/1:  60%|█████▉    | 122/204 [46:38<32:23, 23.70s/it]

Epoch 1/1:  60%|██████    | 123/204 [47:01<31:55, 23.65s/it]

Epoch 1/1:  61%|██████    | 124/204 [47:25<31:29, 23.61s/it]

Epoch 1/1:  61%|██████▏   | 125/204 [47:48<31:04, 23.60s/it]

Epoch 1/1:  62%|██████▏   | 126/204 [48:12<30:42, 23.62s/it]

Epoch 1/1:  62%|██████▏   | 127/204 [48:35<30:16, 23.60s/it]

Epoch 1/1:  63%|██████▎   | 128/204 [48:59<29:55, 23.63s/it]

Epoch 1/1:  63%|██████▎   | 129/204 [49:24<29:50, 23.87s/it]

Epoch 1/1:  64%|██████▎   | 130/204 [49:47<29:22, 23.82s/it]

Epoch 1/1:  64%|██████▍   | 131/204 [50:11<28:56, 23.79s/it]

Epoch 1/1:  65%|██████▍   | 132/204 [50:35<28:32, 23.78s/it]

Epoch 1/1:  65%|██████▌   | 133/204 [50:59<28:09, 23.80s/it]

Epoch 1/1:  66%|██████▌   | 134/204 [51:23<27:54, 23.93s/it]

Epoch 1/1:  66%|██████▌   | 135/204 [51:47<27:29, 23.90s/it]

Epoch 1/1:  67%|██████▋   | 136/204 [52:10<27:01, 23.84s/it]

Epoch 1/1:  67%|██████▋   | 137/204 [52:34<26:42, 23.91s/it]

Epoch 1/1:  68%|██████▊   | 138/204 [52:59<26:31, 24.12s/it]

Epoch 1/1:  68%|██████▊   | 139/204 [53:23<25:59, 23.99s/it]

Epoch 1/1:  69%|██████▊   | 140/204 [53:47<25:33, 23.95s/it]

Epoch 1/1:  69%|██████▉   | 141/204 [54:10<25:08, 23.94s/it]

Epoch 1/1:  70%|██████▉   | 142/204 [54:34<24:41, 23.90s/it]

Epoch 1/1:  70%|███████   | 143/204 [54:58<24:15, 23.87s/it]

Epoch 1/1:  71%|███████   | 144/204 [55:22<23:56, 23.94s/it]

Epoch 1/1:  71%|███████   | 145/204 [55:47<23:50, 24.24s/it]

Epoch 1/1:  72%|███████▏  | 146/204 [56:11<23:24, 24.21s/it]

Epoch 1/1:  72%|███████▏  | 147/204 [56:35<22:55, 24.13s/it]

Epoch 1/1:  73%|███████▎  | 148/204 [56:59<22:29, 24.09s/it]

Epoch 1/1:  73%|███████▎  | 149/204 [57:23<22:01, 24.03s/it]

Epoch 1/1:  74%|███████▎  | 150/204 [57:47<21:36, 24.00s/it]

Epoch 1/1:  74%|███████▍  | 151/204 [58:11<21:11, 23.99s/it]

Epoch 1/1:  75%|███████▍  | 152/204 [58:35<20:47, 23.99s/it]

Epoch 1/1:  75%|███████▌  | 153/204 [59:00<20:40, 24.33s/it]

Epoch 1/1:  75%|███████▌  | 154/204 [59:24<20:14, 24.30s/it]

Epoch 1/1:  76%|███████▌  | 155/204 [59:48<19:44, 24.18s/it]

Epoch 1/1:  76%|███████▋  | 156/204 [1:00:12<19:17, 24.12s/it]

Epoch 1/1:  77%|███████▋  | 157/204 [1:00:36<18:50, 24.06s/it]

Epoch 1/1:  77%|███████▋  | 158/204 [1:01:00<18:26, 24.06s/it]

Epoch 1/1:  78%|███████▊  | 159/204 [1:01:25<18:15, 24.34s/it]

Epoch 1/1:  78%|███████▊  | 160/204 [1:01:50<17:55, 24.45s/it]

Epoch 1/1:  79%|███████▉  | 161/204 [1:02:14<17:27, 24.37s/it]

Epoch 1/1:  79%|███████▉  | 162/204 [1:02:38<16:59, 24.27s/it]

Epoch 1/1:  80%|███████▉  | 163/204 [1:03:02<16:32, 24.21s/it]

Epoch 1/1:  80%|████████  | 164/204 [1:03:26<16:07, 24.19s/it]

Epoch 1/1:  81%|████████  | 165/204 [1:03:50<15:42, 24.16s/it]

Epoch 1/1:  81%|████████▏ | 166/204 [1:04:16<15:32, 24.53s/it]

Epoch 1/1:  82%|████████▏ | 167/204 [1:04:40<15:05, 24.46s/it]

Epoch 1/1:  82%|████████▏ | 168/204 [1:05:04<14:37, 24.37s/it]

Epoch 1/1:  83%|████████▎ | 169/204 [1:05:28<14:10, 24.29s/it]

Epoch 1/1:  83%|████████▎ | 170/204 [1:05:53<13:47, 24.33s/it]

Epoch 1/1:  84%|████████▍ | 171/204 [1:06:17<13:22, 24.32s/it]

Epoch 1/1:  84%|████████▍ | 172/204 [1:06:43<13:12, 24.75s/it]

Epoch 1/1:  85%|████████▍ | 173/204 [1:07:07<12:42, 24.61s/it]

Epoch 1/1:  85%|████████▌ | 174/204 [1:07:31<12:14, 24.47s/it]

Epoch 1/1:  86%|████████▌ | 175/204 [1:07:56<11:48, 24.44s/it]

Epoch 1/1:  86%|████████▋ | 176/204 [1:08:20<11:22, 24.38s/it]

Epoch 1/1:  87%|████████▋ | 177/204 [1:08:44<10:56, 24.31s/it]

Epoch 1/1:  87%|████████▋ | 178/204 [1:09:10<10:41, 24.66s/it]

Epoch 1/1:  88%|████████▊ | 179/204 [1:09:34<10:14, 24.58s/it]

Epoch 1/1:  88%|████████▊ | 180/204 [1:09:58<09:49, 24.58s/it]

Epoch 1/1:  89%|████████▊ | 181/204 [1:10:23<09:25, 24.59s/it]

Epoch 1/1:  89%|████████▉ | 182/204 [1:10:48<09:01, 24.59s/it]

Epoch 1/1:  90%|████████▉ | 183/204 [1:11:13<08:42, 24.88s/it]

Epoch 1/1:  90%|█████████ | 184/204 [1:11:38<08:15, 24.80s/it]

Epoch 1/1:  91%|█████████ | 185/204 [1:12:02<07:49, 24.69s/it]

Epoch 1/1:  91%|█████████ | 186/204 [1:12:26<07:21, 24.54s/it]

Epoch 1/1:  92%|█████████▏| 187/204 [1:12:51<06:56, 24.48s/it]

Epoch 1/1:  92%|█████████▏| 188/204 [1:13:16<06:35, 24.73s/it]

Epoch 1/1:  93%|█████████▎| 189/204 [1:13:40<06:09, 24.61s/it]

Epoch 1/1:  93%|█████████▎| 190/204 [1:14:05<05:42, 24.49s/it]

Epoch 1/1:  94%|█████████▎| 191/204 [1:14:29<05:17, 24.42s/it]

Epoch 1/1:  94%|█████████▍| 192/204 [1:14:54<04:53, 24.48s/it]

Epoch 1/1:  95%|█████████▍| 193/204 [1:15:19<04:31, 24.68s/it]

Epoch 1/1:  95%|█████████▌| 194/204 [1:15:43<04:04, 24.43s/it]

Epoch 1/1:  96%|█████████▌| 195/204 [1:16:06<03:38, 24.27s/it]

Epoch 1/1:  96%|█████████▌| 196/204 [1:16:31<03:13, 24.22s/it]

Epoch 1/1:  97%|█████████▋| 197/204 [1:16:55<02:50, 24.29s/it]

Epoch 1/1:  97%|█████████▋| 198/204 [1:17:20<02:26, 24.36s/it]

Epoch 1/1:  98%|█████████▊| 199/204 [1:17:44<02:02, 24.44s/it]

Epoch 1/1:  98%|█████████▊| 200/204 [1:18:08<01:37, 24.31s/it]

Epoch 1/1:  99%|█████████▊| 201/204 [1:18:32<01:12, 24.19s/it]

Epoch 1/1:  99%|█████████▉| 202/204 [1:18:56<00:48, 24.09s/it]

Epoch 1/1: 100%|█████████▉| 203/204 [1:19:20<00:23, 23.99s/it]

Epoch 1/1: 100%|██████████| 204/204 [1:19:35<00:00, 23.41s/it]

Epoch 1, Train Loss: 1.385, Train Acc: 0.374
Epoch 1 finished


In [27]:
# Validation loop
with torch.no_grad():
    emotion_model.eval()  # Set the model to evaluation mode
    valid_loss = 0.0
    correct_predictions = 0
    total_predictions = 0
    for batch in val_loader:
        # get the inputs
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        # forward
        outputs = emotion_model(input_ids=input_ids, attention_mask=attention_mask)
        loss = criterion(outputs, labels)

        # calculate accuracy
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

        # calculate running loss
        valid_loss += loss.item()

    avg_loss = valid_loss / len(val_loader)
    avg_acc = correct_predictions / total_predictions
    print(f'Validation Loss: {avg_loss:.3f}, Validation Acc: {avg_acc:.3f}')

Validation Loss: 1.302, Validation Acc: 0.428


In [28]:

# Test loop
with torch.no_grad():
    emotion_model.eval()  # Set the model to evaluation mode
    test_loss = 0.0
    correct_predictions = 0
    total_predictions = 0
    for batch in test_loader:
        # get the inputs
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        # forward
        outputs = emotion_model(input_ids=input_ids, attention_mask=attention_mask)
        loss = criterion(outputs, labels)

        # calculate accuracy
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

        # calculate running loss
        test_loss += loss.item()

    avg_loss = test_loss / len(test_loader)
    avg_acc = correct_predictions / total_predictions
    print(f'Test Loss: {avg_loss:.3f}, Test Acc: {avg_acc:.3f}')


Test Loss: 1.338, Test Acc: 0.393


In [29]:
# save the model
torch.save(emotion_model.state_dict(), 'Models/emotion_model.pth')
